version: 2.1
orbs:
  node: circleci/node@5

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: "Installation des dépendances"
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: "Build terminé avec succès"
          command: echo "Build terminé avec succès"

  tests:
    executor: node/default
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./test-results/
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: "Installation des dépendances Jest"
          command: npm install jest-junit
      - run:
          name: "Vérification de Jest"
          command: npm list jest || npm install -g jest
      - run:
          name: "Exécution des tests unitaires"
          command: npm run test:ci
      - store_test_results:
          path: ./test-results/
      - store_artifacts:
          path: ./test-results/
          destination: test-results
      - run: echo "Tests terminés avec succès"

  deploy_dev:
    executor: node/default
    steps:
      - checkout
      - run: echo "Déploiement sur l'environnement **DEVELOPMENT** en cours..."

  deploy_integration:
    executor: node/default
    steps:
      - checkout
      - run: echo "Déploiement sur l'environnement **INTEGRATION** en cours..."

  deploy_prod:
    executor: node/default
    steps:
      - checkout
      - run: echo "Déploiement sur l'environnement **PRODUCTION** en cours..."

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - tests:
          requires:
            - build
      - deploy_dev:
          requires:
            - tests
          filters:
            branches:
              only: develop
      - deploy_integration:
          requires:
            - tests
          filters:
            branches:
              only: integration
      - deploy_prod:
          requires:
            - tests
          filters:
            branches:
              only: main
